#!/usr/bin/env bash
# =============================================================================
# sync-learnings.sh - Sync Local Learnings to Outer-World-Context
# =============================================================================
# Scans watched repositories for learnings marked for promotion and syncs
# them to the outer-world-context repository.
#
# Usage:
#   ./sync/sync-learnings.sh
#   ./sync/sync-learnings.sh --dry-run
#   ./sync/sync-learnings.sh --repo /path/to/toolchain-2026
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPANION_DIR="$(dirname "$SCRIPT_DIR")"

# Default watched repos (can be overridden)
WATCHED_REPOS=(
    "$(dirname "$COMPANION_DIR")/toolchain-2026"
    "$COMPANION_DIR"
)
OUTER_WORLD_REPO="${OUTER_WORLD_REPO:-$(dirname "$COMPANION_DIR")/outer-world-context}"
DRY_RUN=false

# Colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[SYNC]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SYNC]${NC} $1"
}

usage() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS]

Sync learnings from watched repos to outer-world-context.

OPTIONS:
    --dry-run              Show what would be synced without making changes
    --repo PATH            Add additional repo to watch
    --outer-world PATH     Path to outer-world-context repo (default: ../outer-world-context)
    --help, -h             Show this help

EXAMPLES:
    # Sync all watched repos
    ./sync/sync-learnings.sh

    # Dry run to see what would be synced
    ./sync/sync-learnings.sh --dry-run
EOF
}

# =============================================================================
# Check Promotion Criteria
# =============================================================================

should_promote() {
    local learning_file="$1"
    local learning_id="$2"
    
    # Check if learning has cross_pollinate marker
    if grep -q "cross_pollinate.*true\|cross-pollinate.*true" "$learning_file" 2>/dev/null; then
        return 0
    fi
    
    # Check for fundamental insights (heuristic)
    if grep -qiE "(fundamental|core|essential|critical|pattern|principle)" "$learning_file" 2>/dev/null; then
        return 0
    fi
    
    return 1
}

# =============================================================================
# Extract Learning Entry
# =============================================================================

extract_learning() {
    local learning_file="$1"
    local learning_id="$2"
    
    # Extract the learning entry from markdown
    # This is a simplified version - could be enhanced with better parsing
    awk "/^## ${learning_id}:/,/^---$|^## LL-[0-9]+:/" "$learning_file" 2>/dev/null | head -n -1 || true
}

# =============================================================================
# Sync Learning
# =============================================================================

sync_learning() {
    local repo_path="$1"
    local learning_file="$2"
    local learning_id="$3"
    local repo_name=$(basename "$repo_path")
    
    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY RUN] Would promote $learning_id from $repo_name"
        return 0
    fi
    
    # Extract learning content
    local learning_content
    learning_content=$(extract_learning "$learning_file" "$learning_id")
    
    if [ -z "$learning_content" ]; then
        log_info "Could not extract $learning_id from $learning_file"
        return 1
    fi
    
    # Append to outer-world global learnings
    local global_learnings="${OUTER_WORLD_REPO}/global-learnings.yaml"
    
    if [ ! -f "$global_learnings" ]; then
        log_info "Creating $global_learnings"
        mkdir -p "$(dirname "$global_learnings")"
        cat > "$global_learnings" << 'EOF'
# Global Learnings - Aggregated from all projects
# Auto-generated by sync-learnings.sh

learnings: []
EOF
    fi
    
    # For now, just log - full YAML merging would require yq or similar
    log_info "Promoting $learning_id from $repo_name to outer-world-context"
    log_info "Note: Full YAML merging requires yq or manual review"
    
    return 0
}

# =============================================================================
# Scan Repository
# =============================================================================

scan_repo() {
    local repo_path="$1"
    local repo_name=$(basename "$repo_path")
    
    if [ ! -d "$repo_path" ]; then
        log_info "Skipping non-existent repo: $repo_path"
        return 0
    fi
    
    log_info "Scanning $repo_name..."
    
    local learning_file="${repo_path}/learning/LEARNING_LOG.md"
    
    if [ ! -f "$learning_file" ]; then
        log_info "No learning log found in $repo_name"
        return 0
    fi
    
    # Extract all learning IDs
    local learning_ids
    learning_ids=$(grep -E "^## LL-[0-9]+:" "$learning_file" | sed 's/^## //;s/:$//' || true)
    
    if [ -z "$learning_ids" ]; then
        log_info "No learnings found in $repo_name"
        return 0
    fi
    
    # Check each learning for promotion
    local promoted=0
    while IFS= read -r learning_id; do
        if should_promote "$learning_file" "$learning_id"; then
            sync_learning "$repo_path" "$learning_file" "$learning_id"
            promoted=$((promoted + 1))
        fi
    done <<< "$learning_ids"
    
    if [ $promoted -gt 0 ]; then
        log_success "Promoted $promoted learning(s) from $repo_name"
    else
        log_info "No learnings to promote from $repo_name"
    fi
}

# =============================================================================
# Main
# =============================================================================

main() {
    # Parse arguments
    while [ $# -gt 0 ]; do
        case "$1" in
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --repo)
                WATCHED_REPOS+=("$2")
                shift 2
                ;;
            --outer-world)
                OUTER_WORLD_REPO="$2"
                shift 2
                ;;
            --help|-h)
                usage
                exit 0
                ;;
            *)
                log_info "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done
    
    log_info "Starting learning sync..."
    log_info "Outer-world repo: $OUTER_WORLD_REPO"
    log_info "Watched repos: ${WATCHED_REPOS[*]}"
    echo ""
    
    # Check outer-world repo exists
    if [ ! -d "$OUTER_WORLD_REPO" ]; then
        log_info "Outer-world-context repo not found: $OUTER_WORLD_REPO"
        log_info "Create it first or specify with --outer-world"
        return 1
    fi
    
    # Scan each watched repo
    for repo in "${WATCHED_REPOS[@]}"; do
        scan_repo "$repo"
        echo ""
    done
    
    log_success "Learning sync complete"
}

main "$@"

